version: "3"


services:
  redis:
    image: redis:alpine
    command: redis-server
  celery:
    restart: always
    build: .
    command: "celery -A FakeCSV worker -l INFO"
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
  web:
    build: .
    image: fakecsv
    command: python manage.py runserver https://fakecsv2021.herokuapp.com:443
    ports:
      - "443:443"
    volumes:
    - .:/app
