version: "3"


services:
  celery:
    restart: always
    build: .
    command: "celery -A FakeCSV worker -l INFO"
    volumes:
      - .:/app
    depends_on:
      - web
  web:
    build: .
    image: fakecsv
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
    - .:/app
