# Generated by Django 3.2.4 on 2021-06-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20210609_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='modified_time',
            field=models.DateField(null=True, verbose_name='Дата изменения'),
        ),
    ]
