# Generated by Django 3.2.4 on 2021-06-10 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_schema_modified_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('specials', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Тип колонки',
                'verbose_name_plural': 'Типы колонок',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя колонки')),
                ('order', models.IntegerField(verbose_name='Порядковый номер')),
                ('col_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.columntype', verbose_name='Тип колонки')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.schema', verbose_name='Таблица')),
            ],
        ),
    ]
