# Generated by Django 3.2.4 on 2021-06-10 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_column_columntype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Separator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('separator', models.CharField(max_length=1, verbose_name='Разделитель')),
                ('description', models.CharField(max_length=32, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='StringCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=1, verbose_name='Символ')),
                ('description', models.CharField(max_length=32, verbose_name='Описание')),
            ],
        ),
        migrations.AlterModelOptions(
            name='column',
            options={'verbose_name': 'Колонка', 'verbose_name_plural': 'Колонки'},
        ),
        migrations.AlterField(
            model_name='columntype',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='columntype',
            name='specials',
            field=models.TextField(null=True, verbose_name='Дополнительные параметры'),
        ),
        migrations.AddField(
            model_name='schema',
            name='separator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.separator'),
        ),
        migrations.AddField(
            model_name='schema',
            name='string_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.stringcharacter'),
        ),
    ]
