# Generated by Django 3.2.4 on 2021-06-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20210610_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='separator',
            options={'verbose_name': 'Разделитель', 'verbose_name_plural': 'Разделители'},
        ),
        migrations.AlterModelOptions(
            name='stringcharacter',
            options={'verbose_name': 'Строковый символ', 'verbose_name_plural': 'Строковые символы'},
        ),
        migrations.AddField(
            model_name='column',
            name='extras',
            field=models.TextField(default='{}', verbose_name='Дополнительные параметры'),
        ),
    ]
