# Generated by Django 3.2.4 on 2021-06-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20210610_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='columntype',
            name='validator',
            field=models.CharField(max_length=32, null=True, verbose_name='Класс-валидатор'),
        ),
    ]
