# Generated by Django 3.2.4 on 2021-06-13 20:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alter_dataset_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='file',
        ),
        migrations.AddField(
            model_name='dataset',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='column',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Дополнительные параметры'),
        ),
        migrations.AlterField(
            model_name='columntype',
            name='specials',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Дополнительные параметры'),
        ),
    ]
