# Generated by Django 3.2.4 on 2021-06-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20210613_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='extras',
            field=models.JSONField(null=True, verbose_name='Дополнительные параметры'),
        ),
        migrations.AlterField(
            model_name='columntype',
            name='specials',
            field=models.JSONField(null=True, verbose_name='Дополнительные параметры'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='data',
            field=models.JSONField(null=True, verbose_name='Данные'),
        ),
    ]
